---
title: Toon en verberg sprites op verschillende achtergronden
hero_image: images/banner.png
description: Toon en verberg sprites op verschillende achtergronden, zodat ze alleen op de juiste pagina's, scènes of niveaus in jouw project verschijnen
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Toon en verberg sprites op verschillende achtergronden
