---
title: Dangos a chuddio corluniau ar wahanol gefnlenni
hero_image: images/banner.png
description: Dangos a chuddio corluniau ar wahanol gefnlenni fel eu bod yn ymddangos ar y tudalennau, y golygfeydd neu'r lefelau cywir yn eich prosiect yn unig
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Dangos a chuddio corluniau ar wahanol gefnlenni
