---
title: Figuren auf verschiedenen Hintergründen ein- und ausblenden
hero_image: images/banner.png
description: Zeige und verberge die Figuren auf verschiedenen Hintergründen, sodass sie nur auf den richtigen Seiten, Szenen oder Ebenen in deinem Projekt angezeigt werden
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Figuren auf verschiedenen Hintergründen ein- und ausblenden
