---
title: Mostrar e esconder atores em diferentes cenários
hero_image: images/banner.png
description: Mostrar e esconder atores em diferentes cenários para que apareçam apenas nas páginas corretas, cenas ou níveis no seu projeto
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Mostrar e esconder atores em diferentes cenários
