---
title: Zobrazte a skryjte postavy na různých pozadích
hero_image: images/banner.png
description: Zobrazte a skryjte postavy na různých pozadích, aby se objevili pouze na správných stránkách, scénách nebo úrovních vašeho projektu
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Zobrazte a skryjte postavy na různých pozadích
