---
title: Mostrar y ocultar objetos en diferentes fondos
hero_image: images/banner.png
description: Show and hide sprites on different backdrops so that they appear only on the correct pages, scenes, or levels in your project
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Mostrar y ocultar objetos en diferentes fondos
