---
title: Pokazuj i ukrywaj duszki na różnych tłach
hero_image: images/banner.png
description: Pokazuj i ukrywaj duszki na różnych tłach, aby pojawiały się tylko na właściwych stronach, scenach lub poziomach w Twoim projekcie
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Pokazuj i ukrywaj duszki na różnych tłach
