---
title: Visa och dölj sprajts på olika bakgrunder
hero_image: images/banner.png
description: Visa och dölj sprajts på olika bakgrunder så att de bara visas på rätt sidor, scener eller nivåer i ditt projekt
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Visa och dölj sprajts på olika bakgrunder
