---
title: Afficher et masquer les sprites sur différents arrière-plans
hero_image: images/banner.png
description: Afficher et masquer les sprites sur différents arrière-plans afin qu'ils n'apparaissent que sur les pages, scènes ou niveaux appropriés de ton projet.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Afficher et masquer les sprites sur différents arrière-plans
