---
title: Mostra e nascondi le immagini su sfondi diversi
hero_image: images/banner.png
description: Mostra e nascondi le immagini su sfondi diversi in modo che appaiano solo nelle giuste pagine, scene o livelli del tuo progetto
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Mostra e nascondi le immagini su sfondi diversi
